### ISSUE TITLE
Running into an issue in the "Creating Indicators..." part of the pipeline

### ISSUE THREAD

**Issue by ptlorenz** [sturlese/numerai_signals_pipeline#2]
yahoo_data.download_data executes correctly and saves parquet files for the 750 ticker chunks but when then moving onto executing 
> create_indicators_io(paths.db_raw, paths.db_indicators)

an error appears (see screenshot attached).
> create_indicators_io 

runs 
> build_indicators_dfs 

which then in turn runs the following with statement:
> with Pool(cpu_count() * 2) as p:
> #logger.info("With Statement works")
> feature_dfs = list(tqdm(p.imap(build_ticker_indicators, dfs_parallel), total=len(dfs_parallel))) 

it seems that the syntax of the last line is correct (since it shows the progress bar), but 
> build_ticker_indicators

is never executed properly as you can see in the screenshot where it jumps back to the "Downloading Phase...".
I have some logger statements at the very beginning of the build_ticker_indicators function which are never executed, leading me to believe the function itself never runs?
(FYI: Also the parquet files are being automatically deleted (as it overwrites the new dir of the db_raw_downloaded I assume))
Unfortunately I can not figure out why,how?

Hardware: Macbook M1 chip
<img width="846" alt="Screenshot 2022-08-18 at 13 47 49" src="https://user-images.githubusercontent.com/61086523/185392024-04ff69ff-1137-407c-a9c0-c296db054b0a.png">
<img width="848" alt="Screenshot 2022-08-18 at 14 16 52" src="https://user-images.githubusercontent.com/61086523/185392587-8bb539c8-52d6-4eee-98c9-d7e3ba2bc9df.png">

**Comment by sturlese** [comment]
That's weird, haven't seen it before. Could be that the way I'm using the multiprocessing Pool doesn't work with the M1 chip (guessing is cheap). You could try to modify the code to not use parallelism and see if it works.
A simpler thing to try would be to just set the number of threads to a fixed smaller number instead of 'cpus multiplied by 2'.

The specs of my linux box (where I run the pipeline with no issues):
AMD Ryzen 9 5950x 16-core processor × 32
Ubuntu 20.04.4 LTS
ROG Crosshair VIII Dark Hero

If you want to avoid downloading the data on each execution, you can set 'skip_download=True' in the configuration.py, DataConfiguration class (it's False by default).

**Comment by ptlorenz** [comment]
Thanks for the feedback.
I got it to work in Anacondas Jupyter Environment locally. 
Don't really know what's different but it works haha!
(Now running into an issue with "gpu_hist" in the xbg model (aka "XGBoost version not compiled with GPU support.") but can hopefully figure that out by myself)!
Appreciate the help!

**Comment by sturlese** [comment]
The easy solution but slower in terms of execution time, as will run on CPU:

model = XGBRegressor(max_depth=5, learning_rate=0.01, n_estimators=2000, n_jobs=-1, colsample_bytree=0.1, random_state=1, silent=True)

You can also compile or install a XGBoost version that supports GPU.
